### PR TITLE
Added Document Highlight Provider and Document Format Provider

### PR DESCRIPTION
**Pull request by TheColorRed**

### CODE REVIEW

**Comment by TheColorRed** [comment]
Addresses issues #16 and #10

**Comment by TheColorRed** [comment]
I couldn't get formatting to work well yet, so the formatter might need to be commented out for now

**Comment by onecentlin** [comment]
@TheColorRed  thank you for the feedback. However, I cannot build and run this commit. There might be some missing files in .vscode folder.

**Comment by TheColorRed** [comment]
Did you `npm install`? Are you getting errors?

**Comment by TheColorRed** [comment]
Okay I see that in .gitignore it was ignoring files in the `.vscode` directory. I have added the files

**Comment by doatech** [comment]
Thank you for your work, I hope it's getting merged soon!

**Comment by yamenarahman** [comment]
@onecentlin won't you merge this ?

**Comment by onecentlin** [comment]
@yamenarahman I will, just give me a little more time... =)

**Comment by MehediDracula** [comment]
waiting for this to be merged

**Comment by yamenarahman** [comment]
no need for waiting now, returned back to sublime after the last release.

**Comment by nivv** [comment]
@onecentlin what's the hold up?

**Comment by onecentlin** [comment]
@TheColorRed I merged this PR, however, I still didn't see `tag match` and `auto indent` fixed in my development environment. Do you have other extensions effect upon the results?
Would you take a look again? What's your profile settings?

**Comment by TheColorRed** [comment]
Try doing an `npm update` then `npm install`

**Comment by yamenarahman** [comment]
Any progress here ?

**Comment by trippo80** [comment]
@onecentlin I understand if you're busy and all - but would it be possible for you to have a more direct communication with @TheColorRed to try to get this merged? Many of us are waiting for this to be fixed.

**Pull request closed without merging**
